name: 내부 배포용 빌드

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: PXSwiftGen 빌드
    runs-on: macos-12
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - 
        name: Cache SPM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      -
        name: 바이너리 빌드
        run: bundle exec rake cli:build
      -
        name: 아티팩트 생성
        run: bundle exec rake release:zip
      -
        name: 아티팩트 업로드
        uses: actions/upload-artifact@v3
        with:
          name: pxswiftgen-binary
          path: .build/pxswiftgen-*.zip
          retention-days: 30
